config/routes.rb
Rails.application.routes.draw do
  resources :checklists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
class Checklist < ApplicationRecord

  has_many :questions, dependent: :destroy
  
  accepts_nested_attributes_for :questions, 
          allow_destroy: true, 
          reject_if: proc { |att| att['title'].blank? }

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :checklist, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :set_checklist, only: [:show, :edit, :update, :destroy]

  # GET /checklists
  # GET /checklists.json
  def index
    @checklists = Checklist.page(params[:page]).per(10)
  end

  # GET /checklists/1
  # GET /checklists/1.json
  def show
  end

  # GET /checklists/new
  def new
    @checklist = Checklist.new
    @checklist.questions.build
  end

  # GET /checklists/1/edit
  def edit
  end

  # POST /checklists
  # POST /checklists.json
  def create
    @checklist = Checklist.new(checklist_params)

    respond_to do |format|
      if @checklist.save
        format.html { redirect_to @checklist, notice: 'Checklist was successfully created.' }
        format.json { render :show, status: :created, location: @checklist }
      else
        format.html { render :new }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checklists/1
  # PATCH/PUT /checklists/1.json
  def update
    respond_to do |format|
      if @checklist.update(checklist_params)
        format.html { redirect_to @checklist, notice: 'Checklist was successfully updated.' }
        format.json { render :show, status: :ok, location: @checklist }
      else
        format.html { render :edit }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklists/1
  # DELETE /checklists/1.json
  def destroy
    @checklist.destroy
    respond_to do |format|
      format.html { redirect_to checklists_url, notice: 'Checklist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checklist
      @checklist = Checklist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def checklist_params
      params
        .require(:checklist)
        .permit(:title, :description,
                questions_attributes: Question.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/_form.html.haml
= simple_form_for(@checklist) do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.input :description
    
  %table.table
    %thead
      %tr
        %th Actions
        %th Question Title
        %th Question Description
        
    %tbody.questions
      = f.simple_fields_for :questions do |builder|
        = render 'question_fields', f: builder
        
  .form-actions
    = f.button :submit
    = link_to_add_association 'Add Question', f, :questions, class: 'btn btn-primary', data: { association_insertion_node: '.questions', association_insertion_method: :append }
    
    
    
    
    
    

app/views/checklists/_question_fields.html.haml
%tr.nested-fields
  %td
    = link_to_remove_association "remove question", f, class: 'btn btn-primary btn-xs' 
    
  %td
    = f.input :title, label: false
  %td
    = f.input :description, label: false

app/views/checklists/edit.html.erb
<h1>Editing Checklist</h1>

<%= render 'form', checklist: @checklist %>

<%= link_to 'Show', @checklist %> |
<%= link_to 'Back', checklists_path %>

app/views/checklists/index.html.haml
%p#notice= notice
%h1 Checklists
%table
  %thead
    %tr
      %th Title
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @checklists.each do |checklist|
      %tr
        %td= checklist.title
        %td= checklist.description
        %td= link_to 'Show', checklist
        %td= link_to 'Edit', edit_checklist_path(checklist)
        %td= link_to 'Destroy', checklist, method: :delete, data: { confirm: 'Are you sure?' }

=paginate @checklists

%br/
= link_to 'New Checklist', new_checklist_path

app/views/checklists/new.html.erb
<h1>New Checklist</h1>

<%= render 'form', checklist: @checklist %>

<%= link_to 'Back', checklists_path %>

app/views/checklists/show.html.haml
%p#notice= notice
%p
  %strong Checklist Title:
  = @checklist.title
%p
  %strong Checklist Description:
  = @checklist.description
  
  
%table.table
  %thead
    %tr
      %th Question Title
      %th Description
        
  %tbody.fields
    - @checklist.questions.each do |question|   
      %tr
        %td 
          = question.title

        %td 
          = question.description

  
= link_to 'Edit', edit_checklist_path(@checklist)
|
\#{link_to 'Back', checklists_path}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>